### ISSUE TITLE
It shouldn't add reset if matchedSelectors.length == 0

### ISSUE THREAD

**Issue by giuseppeg** [maximkoretskiy/postcss-autoreset#19]
Hi @maximkoretskiy it seems that the plugin adds a reset even when `matchedSelectors.length` is `0`. This is what I see:

```css
{
  /* reset rules */
}

/* my css */
```

**Comment by giuseppeg** [comment]
@simonsmith blocker for us ^

**Comment by simonsmith** [comment]
An easy fix I expect?
