### ISSUE TITLE
reset font and color properties without `all: unset`. possible?

### ISSUE THREAD

**Issue by iamstarkov** [maximkoretskiy/postcss-autoreset#2]
I understand, that its quite out of scope, but still it tightly relates to autoreset, so only reason i’m asking, because I assume you made some investigation in this area. (because `all: unset`, [is not here](http://caniuse.com/#feat=css-unset-value) yet currently). How do you think is there any way to reset font and color properties without `all: unset`?

**Comment by iamstarkov** [comment]
Just found https://github.com/maximkoretskiy/postcss-initial and its wonderfull

**Comment by iamstarkov** [comment]
Just found https://github.com/maximkoretskiy/postcss-initial and its wonderfull

**Comment by maximkoretskiy** [comment]
thanks)
