### ISSUE TITLE
all: initial and svg elements

### ISSUE THREAD

**Issue by meleyal** [maximkoretskiy/postcss-autoreset#21]
`all: initial` seems to break svg elements. Do you know of any workarounds for this?

**Comment by maximkoretskiy** [comment]
Hi! You can exclude svg elements from reset scope with [rulesMatcher](https://github.com/maximkoretskiy/postcss-autoreset#rulesmatcher) or use another [reset](https://github.com/maximkoretskiy/postcss-autoreset#reset) value that doesn't break svg. Is it suitable solution?

**Comment by maximkoretskiy** [comment]
@meleyal ^

**Comment by meleyal** [comment]
Thanks 👍
