### ISSUE TITLE
Keyframes key point treated like class names

### ISSUE THREAD

**Issue by copycut** [maximkoretskiy/postcss-autoreset#22]
```
@keyframes fadeInUp {
  0% {
    opacity: 0;
    transform: translate3d(0, 100%, 0);
  }

  100% {
    opacity: 1;
    transform: none;
  }
}
```

in combination with 
``` 
require('postcss-autoreset')({
  reset: {
    boxSizing: 'border-box'
  }
}),
```

give after build:

```
0%,
100%,
.changePassword--1RUhp,
.changePassword--1RUhp .logo--MTlfo,
.title--1jDOc,
.form--3A4Qh,
.field--12t7f,
.label--3qBxI,
.input--oN5FM,
.link--3hkxd {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}
```

Even with `from`, `to`, theses key names are taken like class name.

**Comment by copycut** [comment]
More details:
The issues appear when my @keyframes rule is set in a common file call in another file through @import rule. ('postcss-partial-import'). So I think we can close it.

**Comment by maximkoretskiy** [comment]
@copycut Hi! And thank U for suggestion. Are U able to make a PR for this issue?

**Comment by copycut** [comment]
I'm still trying to reproduce that in a isolate project. But if it can be fixed, yes.

**Comment by maximkoretskiy** [comment]
I'll try to check the bug today.

**Comment by maximkoretskiy** [comment]
@copycut hi! Just published fixed version to npm.
