### ISSUE TITLE
Use postcss-js to parse reset properties

### ISSUE THREAD

**Issue by ai** [maximkoretskiy/postcss-autoreset#3]
Right now I need to use string key for `"box-sizing"`. But if you use [postcss-js](https://github.com/postcss/postcss-js) it will allow me to use `boxSizing`. Also [postcss-js] is used in `postcss-mixin`, so it will increase constistency.

**Comment by ai** [comment]
@maximkoretskiy please telll me if you have no time, I will send a PR :)

**Comment by maximkoretskiy** [comment]
https://github.com/maximkoretskiy/postcss-autoreset/pull/5
