### ISSUE TITLE
Missing dist folder in 3.0.0 release

### ISSUE THREAD

**Issue by mach25** [maximkoretskiy/postcss-autoreset#31]
I'm trying to install version 3.0.0 and it's missing the dist folder so it's not possible to use the plugin.

**Comment by mminkoff** [comment]
Just a stopgap, but `npm install --save-dev postcss postcss-autoreset@2.0.2` should work until this is fixed.

**Comment by maximkoretskiy** [comment]
@mach25 @mminkoff just released the fix. 

Thank you for issue!

**Comment by justafish** [comment]
The 3.0.1 release still isn't working for me -
```
[16:36:33] Error: Cannot find module './lib'
Require stack:
- /home/justafish/Repos/wombat/node_modules/postcss-autoreset/index.js
```

**Comment by justafish** [comment]
@maximkoretskiy it's working now, thank you!
