### ISSUE TITLE
Pseudoclasses

### ISSUE THREAD

**Issue by kinday** [maximkoretskiy/postcss-autoreset#7]
Hi!

Maybe we can have an option to skip pseudoclass resetting? I know we can handle it with the help of `rulesMatcher`, but for me this case seems as a widespread one.

If you support the idea, I’ll implement it.

And by the way thanks for the awesome plugin.

**Comment by maximkoretskiy** [comment]
Hi! Nice idea! 

I`m not finally sure than we need option for that.

For my mind it should be default for bem and suit matchers.
